version: '3.8'

services:
  # ================================
  # Base de datos PostgreSQL (en Docker)
  # ================================
  db:
    image: postgres:17-alpine
    container_name: mte_postgres_local
    environment:
      POSTGRES_DB: ${name_db}
      POSTGRES_USER: ${user_postgres}
      POSTGRES_PASSWORD: ${password_user_postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${user_postgres} -d ${name_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ================================
  # Redis para Celery (en Docker)
  # ================================
  redis:
    image: redis:7-alpine
    container_name: mte_redis_local
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    ports:
      - "6379:6379"
    volumes:
      - redis_data_local:/data
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-defaultpassword}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ================================
  # Backend Django (conecta a PostgreSQL y Redis Docker)
  # ================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    container_name: mte_backend_local
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}
      - name_db=${name_db}
      - user_postgres=${user_postgres}
      - password_user_postgres=${password_user_postgres}
      - port_postgres=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - SCADA_BASE_URL=${SCADA_BASE_URL}
      - SCADA_USERNAME=${SCADA_USERNAME}
      - SCADA_PASSWORD=${SCADA_PASSWORD}
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,nginx
      - DJANGO_SETTINGS_MODULE=core.settings
      - POSTGRES_HOST=db
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.git
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # ================================
  # Worker de Celery (conecta a PostgreSQL y Redis Docker)
  # ================================
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: mte_celery_worker_local
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}
      - name_db=${name_db}
      - user_postgres=${user_postgres}
      - password_user_postgres=${password_user_postgres}
      - port_postgres=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - SCADA_BASE_URL=${SCADA_BASE_URL}
      - SCADA_USERNAME=${SCADA_USERNAME}
      - SCADA_PASSWORD=${SCADA_PASSWORD}
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: celery -A core worker -l info --concurrency=2

  # ================================
  # Scheduler de Celery Beat (conecta a PostgreSQL y Redis Docker)
  # ================================
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: mte_celery_beat_local
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY}
      - name_db=${name_db}
      - user_postgres=${user_postgres}
      - password_user_postgres=${password_user_postgres}
      - port_postgres=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultpassword}
      - SCADA_BASE_URL=${SCADA_BASE_URL}
      - SCADA_USERNAME=${SCADA_USERNAME}
      - SCADA_PASSWORD=${SCADA_PASSWORD}
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./celerybeat-schedule:/app/celerybeat-schedule
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mte_network_local
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

  # ================================
  # Frontend React
  # ================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: mte_frontend_local
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ================================
  # Nginx como Proxy Reverso
  # ================================
  nginx:
    image: nginx:alpine
    container_name: mte_nginx_local
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/var/www/static:ro
      - ./media:/var/www/media:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mte_network_local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ================================
# Volumes
# ================================
volumes:
  postgres_data_local:
    driver: local
  redis_data_local:
    driver: local

# ================================
# Networks
# ================================
networks:
  mte_network_local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
