# Generated by Django 5.2.4 on 2025-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Indicador')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('source', models.CharField(max_length=100, verbose_name='Fuente de Datos')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
