# Generated by Django 5.2.4 on 2025-07-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumptionKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_consumption_current_month', models.FloatField(default=0.0, help_text='Consumo total acumulado del mes actual en kWh.')),
                ('total_consumption_previous_month', models.FloatField(default=0.0, help_text='Consumo total acumulado del mes anterior en kWh.')),
                ('last_calculated', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última vez que se calculó este KPI.')),
            ],
            options={
                'verbose_name': 'KPI de Consumo Mensual',
                'verbose_name_plural': 'KPIs de Consumo Mensual',
            },
        ),
        migrations.DeleteModel(
            name='Indicator',
        ),
    ]
