# Generated by Django 5.2.4 on 2025-07-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_monthlyconsumptionkpi_delete_indicator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyconsumptionkpi',
            options={'verbose_name': 'KPI de Consumo y Generación Mensual', 'verbose_name_plural': 'KPIs de Consumo y Generación Mensual'},
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='total_generation_current_month',
            field=models.FloatField(default=0.0, help_text='Generación total acumulada del mes actual en Wh.'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='total_generation_previous_month',
            field=models.FloatField(default=0.0, help_text='Generación total acumulada del mes anterior en Wh.'),
        ),
    ]
