# Generated by Django 5.2.4 on 2025-07-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_monthlyconsumptionkpi_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyconsumptionkpi',
            name='total_exported_current_month',
        ),
        migrations.RemoveField(
            model_name='monthlyconsumptionkpi',
            name='total_exported_previous_month',
        ),
        migrations.RemoveField(
            model_name='monthlyconsumptionkpi',
            name='total_imported_current_month',
        ),
        migrations.RemoveField(
            model_name='monthlyconsumptionkpi',
            name='total_imported_previous_month',
        ),
    ]
