# Generated by Django 5.2.4 on 2025-07-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_monthlyconsumptionkpi_avg_instantaneous_power_current_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_daily_temp_current_month',
            field=models.FloatField(default=0.0, help_text='Temperatura promedio diaria del mes actual en °C.'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_daily_temp_previous_month',
            field=models.FloatField(default=0.0, help_text='Temperatura promedio diaria del mes anterior en °C.'),
        ),
    ]
