# Generated by Django 5.2.4 on 2025-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_monthlyconsumptionkpi_avg_daily_temp_current_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_relative_humidity_current_month',
            field=models.FloatField(default=0.0, help_text='Humedad relativa promedio del mes actual en %RH.'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_relative_humidity_previous_month',
            field=models.FloatField(default=0.0, help_text='Humedad relativa promedio del mes anterior en %RH.'),
        ),
    ]
