# Generated by Django 5.2.4 on 2025-07-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_monthlyconsumptionkpi_avg_relative_humidity_current_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_wind_speed_current_month',
            field=models.FloatField(default=0.0, help_text='Velocidad del viento promedio del mes actual en km/h.'),
        ),
        migrations.AddField(
            model_name='monthlyconsumptionkpi',
            name='avg_wind_speed_previous_month',
            field=models.FloatField(default=0.0, help_text='Velocidad del viento promedio del mes anterior en km/h.'),
        ),
    ]
