# Generated by Django 5.2.4 on 2025-08-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_monthlyconsumptionkpi_avg_wind_speed_current_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del registro.', unique=True)),
                ('daily_consumption', models.FloatField(default=0.0, help_text='Consumo total diario en kWh.')),
                ('daily_generation', models.FloatField(default=0.0, help_text='Generación total diaria en Wh.')),
            ],
            options={
                'verbose_name': 'Datos Diarios para Gráficos',
                'verbose_name_plural': 'Datos Diarios para Gráficos',
                'ordering': ['date'],
            },
        ),
    ]
