# Generated by Django 5.2.4 on 2025-08-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_dailychartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailychartdata',
            name='daily_balance',
            field=models.FloatField(default=0.0, help_text='Balance energético diario (generación - consumo).'),
        ),
    ]
