# Generated by Django 5.2.4 on 2025-08-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_dailychartdata_daily_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailychartdata',
            options={'verbose_name': 'Datos Diarios de Gráfico', 'verbose_name_plural': 'Datos Diarios de Gráfico'},
        ),
        migrations.AddField(
            model_name='dailychartdata',
            name='avg_daily_temp',
            field=models.FloatField(default=0.0, help_text='Temperatura promedio diaria en °C.'),
        ),
        migrations.AlterField(
            model_name='dailychartdata',
            name='daily_balance',
            field=models.FloatField(default=0.0, help_text='Balance energético diario (Generación en kWh - Consumo en kWh).'),
        ),
    ]
