# Generated by Django 5.2.4 on 2025-08-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_alter_dailychartdata_options_and_more'),
        ('scada_proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeterChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del registro.')),
                ('hourly_consumption', models.JSONField(default=list, help_text='Consumo por hora del día en kWh.')),
                ('daily_consumption', models.FloatField(default=0.0, help_text='Consumo total del día en kWh.')),
                ('peak_hour', models.IntegerField(default=0, help_text='Hora del pico de consumo (0-23).')),
                ('peak_value', models.FloatField(default=0.0, help_text='Valor del pico de consumo en kW.')),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora del cálculo.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='scada_proxy.institution')),
            ],
            options={
                'verbose_name': 'Datos de Gráfico de Medidor Eléctrico',
                'verbose_name_plural': 'Datos de Gráficos de Medidores Eléctricos',
                'indexes': [models.Index(fields=['device', 'date'], name='indicators__device__28a906_idx'), models.Index(fields=['institution', 'date'], name='indicators__institu_0ee5fa_idx'), models.Index(fields=['date'], name='indicators__date_dc7917_idx')],
                'unique_together': {('device', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ElectricMeterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del registro (para datos diarios) o primer día del mes (para datos mensuales).')),
                ('time_range', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], help_text='Tipo de rango de tiempo del registro.', max_length=20)),
                ('cumulative_active_power', models.FloatField(default=0.0, help_text='Energía activa acumulada en kWh.')),
                ('total_active_power', models.FloatField(default=0.0, help_text='Total de energía activa consumida en kWh.')),
                ('peak_demand', models.FloatField(default=0.0, help_text='Demanda pico en kW.')),
                ('avg_demand', models.FloatField(default=0.0, help_text='Demanda promedio en kW.')),
                ('measurement_count', models.IntegerField(default=0, help_text='Número de mediciones procesadas.')),
                ('last_measurement_date', models.DateTimeField(blank=True, help_text='Fecha de la última medición procesada.', null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora del cálculo.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_consumption', to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_consumption', to='scada_proxy.institution')),
            ],
            options={
                'verbose_name': 'Consumo de Medidor Eléctrico',
                'verbose_name_plural': 'Consumos de Medidores Eléctricos',
                'indexes': [models.Index(fields=['device', 'date', 'time_range'], name='indicators__device__3ed751_idx'), models.Index(fields=['institution', 'date', 'time_range'], name='indicators__institu_6def42_idx'), models.Index(fields=['date', 'time_range'], name='indicators__date_f49e70_idx')],
                'unique_together': {('device', 'date', 'time_range')},
            },
        ),
    ]
