# Generated by Django 5.2.4 on 2025-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_electricmeterchartdata_electricmeterconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyconsumptionkpi',
            name='total_generation_current_month',
            field=models.FloatField(default=0.0, help_text='Generación total acumulada del mes actual en kWh.'),
        ),
    ]
