# Generated by Django 5.2.4 on 2025-08-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_alter_monthlyconsumptionkpi_total_generation_current_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychartdata',
            name='daily_balance',
            field=models.FloatField(default=0.0, help_text='Balance energético diario en kWh.'),
        ),
        migrations.AlterField(
            model_name='dailychartdata',
            name='daily_generation',
            field=models.FloatField(default=0.0, help_text='Generación total diaria en kWh.'),
        ),
        migrations.AlterField(
            model_name='dailychartdata',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='monthlyconsumptionkpi',
            name='total_generation_previous_month',
            field=models.FloatField(default=0.0, help_text='Generación total acumulada del mes anterior en kWh.'),
        ),
    ]
