# Generated by Django 5.2.4 on 2025-08-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_alter_dailychartdata_daily_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychartdata',
            name='date',
            field=models.DateField(help_text='Fecha del registro.', unique=True),
        ),
    ]
