# Generated by Django 5.2.4 on 2025-08-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0016_alter_dailychartdata_date'),
        ('scada_proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricMeterEnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], max_length=20)),
                ('imported_energy_low', models.FloatField(default=0.0)),
                ('imported_energy_high', models.FloatField(default=0.0)),
                ('total_imported_energy', models.FloatField(default=0.0)),
                ('exported_energy_low', models.FloatField(default=0.0)),
                ('exported_energy_high', models.FloatField(default=0.0)),
                ('total_exported_energy', models.FloatField(default=0.0)),
                ('net_energy_consumption', models.FloatField(default=0.0)),
                ('measurement_count', models.IntegerField(default=0)),
                ('last_measurement_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada_proxy.device')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scada_proxy.institution')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'date', 'time_range'], name='indicators__device__e46f41_idx'), models.Index(fields=['institution', 'date', 'time_range'], name='indicators__institu_48abaf_idx')],
                'unique_together': {('device', 'institution', 'date', 'time_range')},
            },
        ),
    ]
