# Generated by Django 5.2.4 on 2025-08-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_weatherstationchartdata_weatherstationindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='ID de la tarea de Celery', max_length=255, unique=True)),
                ('user_id', models.IntegerField(help_text='ID del usuario que solicitó el reporte')),
                ('report_type', models.CharField(help_text='Tipo de reporte generado', max_length=100)),
                ('category', models.CharField(help_text='Categoría de dispositivo', max_length=50)),
                ('institution_id', models.IntegerField(help_text='ID de la institución')),
                ('institution_name', models.CharField(help_text='Nombre de la institución', max_length=255)),
                ('devices', models.JSONField(default=list, help_text='Lista de IDs de dispositivos')),
                ('time_range', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], help_text='Rango de tiempo del reporte', max_length=20)),
                ('start_date', models.DateField(help_text='Fecha de inicio del reporte')),
                ('end_date', models.DateField(help_text='Fecha de fin del reporte')),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF'), ('Excel', 'Excel')], help_text='Formato del reporte', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', help_text='Estado de generación del reporte', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Ruta del archivo generado', max_length=500, null=True)),
                ('file_size', models.CharField(blank=True, help_text="Tamaño del archivo (ej: '2.5 MB')", max_length=20, null=True)),
                ('record_count', models.IntegerField(default=0, help_text='Número de registros en el reporte')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló la generación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Fecha de finalización', null=True)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='indicators__user_id_67e4d6_idx'), models.Index(fields=['institution_id', 'category'], name='indicators__institu_c2f284_idx'), models.Index(fields=['created_at'], name='indicators__created_18c571_idx'), models.Index(fields=['task_id'], name='indicators__task_id_9e71de_idx')],
            },
        ),
    ]
