# Generated by Django 5.2.4 on 2025-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('progress', models.FloatField(default=0.0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
