# Generated by Django 5.2.4 on 2025-07-19 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_proxy', '0002_taskprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='taskprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='processed_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='total_devices',
            field=models.IntegerField(default=0),
        ),
    ]
