# Generated by Django 5.2.4 on 2025-07-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada_proxy', '0003_remove_taskprogress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
