# Generated by Django 5.2.4 on 2025-08-19 03:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Clave del token')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del dispositivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Último uso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Token activo')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de dispositivo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Autenticación',
                'verbose_name_plural': 'Tokens de Autenticación',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de refresco')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Token activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Refresco',
                'verbose_name_plural': 'Tokens de Refresco',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP de acceso')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última actividad')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos de login')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('password_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Contraseña cambiada el')),
                ('require_password_change', models.BooleanField(default=False, verbose_name='Requiere cambio de contraseña')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de teléfono')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='2FA habilitado')),
                ('backup_codes', models.JSONField(default=list, verbose_name='Códigos de respaldo')),
                ('notification_preferences', models.JSONField(default=dict, verbose_name='Preferencias de notificación')),
                ('theme_preference', models.CharField(default='light', max_length=20, verbose_name='Tema preferido')),
                ('language', models.CharField(default='es', max_length=10, verbose_name='Idioma preferido')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Nombre de usuario')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('failed', 'Fallido'), ('locked', 'Cuenta bloqueada')], max_length=20, verbose_name='Estado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Razón del fallo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='authenticat_usernam_69bd25_idx'), models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_95756c_idx')],
            },
        ),
    ]
